### ISSUE TITLE
Remove RabbitMQ from the list of softwares used

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/CloudCV#101]
### Deliverables
Remove RabbitMQ from the *open source softwares used* on the homepage, since RabbitMQ has been removed from EvalAI project and the website needs to be updated with new technology used.

@deshraj @RishabhJain2018

**Comment by impiyush83** [comment]
@gautamjajoo  Can i work on this ?

**Comment by RishabhJain2018** [comment]
Sure!
