### ISSUE TITLE
Error, while using the command to "clone", mentioned in README

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/CloudCV#21]
**Command** -> git clone git@github.com:Cloud-CV/CloudCV.git cloudcv

**Observed Behaviour:**

~$ git clone git@github.com:Cloud-CV/CloudCV.git cloudcv
Cloning into 'cloudcv'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Actual Behaviour:**

The command should clone the project.

**Amendment:**

Command should be changed to : 

git clone https://github.com/Cloud-CV/CloudCV.git cloudcv

**Comment by uttu357** [comment]
This behavior will be observed if you have not added your ssh keys to your GitHub account. For non ssh users the second command will work.

**Comment by HargovindArora** [comment]
@uttu357 So shouldn't we mention in the README, like for non ssh users?

**Comment by uttu357** [comment]
Sure feel free to make a PR fixing this! 👍

**Comment by HargovindArora** [comment]
@uttu357 Okay. Working on it.
