### ISSUE TITLE
Command to change settings.sample.py to settings.py is incorrect.

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/CloudCV#22]
The directory mentioned i.e. `settings/dev.sample.py` is incorrect rather it should be `settings/dev/settings.sample.py .

**Mentioned Command** -> `cp settings/dev.sample.py settings/dev.py` 

**Amendment required** -> `cp settings/dev/settings.sample.py settings/dev/dev.py`

**Comment by uttu357** [comment]
The line mentioned in the readme is `cp settings/dev/settings.sample.py settings/dev/settings.py` which is correct.
