### ISSUE TITLE
Screenshot image file input in homepage does not have any styles.

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/CloudCV#38]
File input on the homepage is not styled.
- The contact-us form in the [homepage](http://cloudcv.us-west-2.elasticbeanstalk.com/contact-us) contains a file input which is not styled and have default html styles. The current form looks like 

![image](https://user-images.githubusercontent.com/21292343/33555494-95d25b9e-d926-11e7-95d7-4d62a6193842.png)

- It can be styled using a wrapper container around the input block. I have changed the styles in my browser's console and now the form looks like

![image](https://user-images.githubusercontent.com/21292343/33555582-f07d82b2-d926-11e7-9877-37fab497c95d.png)

- The design of input can be altered as per need.

I would like to work to resolve this UI issue.

**Comment by uttu357** [comment]
Sure. Go ahead and make a PR. Make sure that the "Choose File" button styling works on latest version of major browsers and fallbacks gracefully on the older browsers that do not support the customization.

**Comment by fristonio** [comment]
How should the choose file button look, Is the above styling fine ?

**Comment by uttu357** [comment]
Yeah the above styling looks fine. :+1:
