### ISSUE TITLE
Add favicon to website

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/CloudCV#51]
### Deliverables
Add CloudCV logo as favicon to the website.

**Comment by uttu357** [comment]
Yeah sure add the logo as a favicon.

**Comment by himanshuc3** [comment]
I would like to take this issue. I'll setup the repo and explore first. Hopefully I could be of some use!

**Comment by gautamjajoo** [comment]
Hey @uttu357 ! I was adding the following code in `webpack.config.dev.js`, but this isn't working, could you tell the reason.
```
 new HtmlWebpackPlugin({
    template: "./src/index.html",
    filename: "./index.html",
    favicon: './src/images/favicon.ico'
    })
```
