### ISSUE TITLE
Add transition to header elements for smooth effect.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/CloudCV#9]
Add transition CSS property to header links so that animation will become smooth.

**Comment by aka-jain** [comment]
#8 @uttu357 please do this change here.

**Comment by uttu357** [comment]
Sure will do this asap! :+1:

**Comment by uttu357** [comment]
@aka-jain Done! Please check! :)

**Comment by uttu357** [comment]
Closed with #8
