### ISSUE TITLE
Fix potential vulnerabilities due to outdated requirements

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/CloudCV#96]
There are some outdated requirements which can open potential security threats. Hence we should update the vulnerable package versions as suggested by Github. Here is the list of upgrades to be done (as suggested by Github):

1. `pyopenssl>=17.5.0`
2. `django>=1.11.15`

Please make sure to verify the validity and compatibility of suggestions with CloudCV codebase.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 I would like to work on it?

**Comment by RishabhJain2018** [comment]
Sure! you can work on it.

**Comment by gautamjajoo** [comment]
Hi @KhalidRmb! I am working on it. :)

**Comment by KhalidRmb** [comment]
#1996 and this seem to address the same.

**Comment by gautamjajoo** [comment]
@KhalidRmb Will you like to work on it? I have other issues to work on.

**Comment by KhalidRmb** [comment]
I'll look into it. :)

**Comment by gautamjajoo** [comment]
@KhalidRmb Sure! Go ahead.
